# Generated by Django 6.0 on 2026-01-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
