# Generated by Django 6.0 on 2026-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Globale'), ('PERSONAL', 'Personale')], default='PERSONAL', max_length=10),
        ),
    ]
