# Generated by Django 6.0 on 2026-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=10),
        ),
    ]
