# Generated by Django 6.0 on 2026-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
