# Generated by Django 6.0 on 2026-02-16 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_transaction_recurrent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Store name')),
                ('card_number', models.CharField(max_length=50, verbose_name='Card number')),
                ('barcode_type', models.CharField(choices=[('code128', 'Code 128'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('code39', 'Code 39'), ('itf', 'ITF')], default='code128', max_length=20, verbose_name='Barcode type')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Barcode image')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty Card',
                'verbose_name_plural': 'Loyalty Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
