# Generated by Django 6.0 on 2026-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_loyaltycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='barcode_type',
            field=models.CharField(choices=[('code128', 'Code 128'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('code39', 'Code 39'), ('itf', 'ITF')], default='code128', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
