# Generated by Django 6.0 on 2026-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loyaltycard_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='barcode_image',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
