# Generated by Django 6.0 on 2026-02-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_loyaltycard_barcode_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltycard',
            options={'ordering': ['store_name'], 'verbose_name': 'Loyalty Card', 'verbose_name_plural': 'Loyalty Cards'},
        ),
    ]
