# Generated by Django 6.0 on 2026-04-13 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_loyaltycard_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('member_1', 'Member 1'), ('member_2', 'Member 2')], help_text='Family accounts only: which member paid.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If active, this transaction will repeat every month.', verbose_name='Monthly Recurring'),
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_1', models.CharField(max_length=100)),
                ('member_2', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
