# Generated by Django 6.0 on 2026-07-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_transaction',
            field=models.ForeignKey(blank=True, help_text='Set on copies derived from a family account transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_transactions', to='core.transaction'),
        ),
    ]
